### ISSUE TITLE
Error regarding the feature optimization part

### ISSUE THREAD

**Issue by BehzadBozorgtabar** [astra-vision/PODA#1]
Hello,

Interesting paper!

There is a size mismatch for running the feature optimization part below.

Traceback (most recent call last):
  File "./PODA/f_aug_with_CLIP.py", line 283, in <module>
	main()
  File "./PODA/f_aug_with_CLIP.py", line 253, in main
	loss_CLIP1 = (1- torch.cosine_similarity(text_target, target_features_from_f1, dim=1)).mean()
RuntimeError: The size of tensor a (16) must match the size of tensor b (15) at non-singleton dimension 0

I'd appreciate it if you could help with this.

Thanks

**Comment by mfahes** [comment]
Hello Behzad, 
Thank you for you interest in our work and for pointing out this issue!
Indeed, it's because the last batch of images doesn't have the same dimension of the target text embedding vector. I fixed it. Please let me know if there's anything else i could help you with!

**Comment by BehzadBozorgtabar** [comment]
Thanks, I appreciate it.

**Comment by cht619** [comment]
I got:
image.shape ] = [bs, 2048, h, w]
text=[bs, 1024]
how to solve it?
