### ISSUE TITLE
Questions about object detection

### ISSUE THREAD

**Issue by 2490o** [astra-vision/PODA#2]
Hello, can you open source the overall code of the detection? I tried to reproduce the code of the detection part, but it did not achieve the desired effect. Can you see how you achieved it?

**Comment by mfahes** [comment]
Hi, for detection we used the same feature augmentation script (PIN_aug.py). The code is based on MMDetection library https://github.com/open-mmlab/mmdetection. Please refer to the implementation details in appendix E of the paper.

**Comment by mfahes** [comment]
I'll close this issue now.

**Comment by tuanhungvu** [comment]
Hello @ZZ2490 , the detection code was released [here](https://github.com/astra-vision/PODA/tree/detection)
