### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by jmwang0117** [astra-vision/PODA#3]
Hello and thank you for your great work.

I encountered an error when running the prediction code. It seems to be a problem with the pytorch version, which prevents the pre-trained model from being loaded. Can you provide the versions of python, pytorch, and torchvision you used for training?

Thanks a lot!

![image](https://github.com/astra-vision/PODA/assets/51500826/4b50c017-954d-47d7-a394-ceaeee9a2340)

**Comment by mfahes** [comment]
Hi, thanks for your interest in our work.
These are the versions used 
python: 3.9.6
torch: 2.0.1+cu117
torchvision: 0.15.2+cu117
Please let me know if this solves the problem

**Comment by jmwang0117** [comment]
> Hi, thanks for your interest in our work. These are the versions used python: 3.9.6 torch: 2.0.1+cu117 torchvision: 0.15.2+cu117 Please let me know if this solves the problem

![image](https://github.com/astra-vision/PODA/assets/51500826/3efafcea-8b34-4da6-a506-e16e659acfdc)

I use Docker:
python: 3.10.11
torch: 2.0.1+cu117

I have a new problem, can you help me solve it? I will encounter this problem when using the provided pre-trained model. I will also encounter this problem in the "Model adaptation" step of training my own model. I guess it is a problem with the pickle version. What version are you using? Or do you have any other solution.

Looking forward to your reply. Thanks!

**Comment by jmwang0117** [comment]
I solve it
