### ISSUE TITLE
Questions about the provided source model

### ISSUE THREAD

**Issue by jmwang0117** [astra-vision/PODA#4]
Hello and thank you for your great work！

I use the CS source model you provided to predict citypaces images, but the visualization results are not very good. Is the source model provided only trained on the source domain without prompt? If a prompt is passed, what is the prompt corresponding to that situation?

![image](https://github.com/astra-vision/PODA/assets/51500826/063bc0c0-e204-4366-8128-ea375dba46c9)
![image](https://github.com/astra-vision/PODA/assets/51500826/9751ad87-5782-4ffe-a27b-ffe695d0c799)

I also evaluated the CS source model on cityscapes' val, and the accuracy was very low. Is it the wrong model?

![image](https://github.com/astra-vision/PODA/assets/51500826/d4deecf9-bb79-403c-828d-28b10be01181)

Looking forward to your reply!

**Comment by jmwang0117** [comment]
solved

**Comment by hedjazi** [comment]
Would you please give us more details? thanks.
