### ISSUE TITLE
Changing backbone to ViT-B/16

### ISSUE THREAD

**Issue by hollow-503** [astra-vision/PODA#5]
Thanks for your great work!
Have you tried using the `ViT-b/16` as a backbone? I was replacing the backbone to align with other work and found that compared to the `ResNet50`, the `ViT-b/16` outputs an extra global token, causing that the features can not be reshaped to  `[B, C, H, W]`.

**Comment by mfahes** [comment]
Hi, thanks for your question.
Indeed, we didn't test ViT architectures, I am not sure if the use of  AdaIN and PIN is straightforward for architectures different from CNNs.

**Comment by hollow-503** [comment]
Thanks for your reply. Actually, I have tested ViT architectures, but it seems it doesn't work.

1) Firstly, I replace the `ResNet50` with `ViT-B/16` and maintain the decoder `DeeplabV3+`, but it only get about 50 mIoU in the source training, which is much lower than the performance of ResNet50.

2) I replace the DeepLabV3+ with the `VisionTransformerUpHead` in [SETR](https://github.com/fudan-zvg/SETR/blob/main/configs/_base_/models/setr_naive_pup.py) to match the ViT-B/16, but it still get about 50 mIoU. 

Do you think PIN and AdaIN have any limitations when using pre-trained ViT of CLIP? Or is there any important part I'm missing that is causing such low performance?

**Comment by mfahes** [comment]
I don't know about using AdaIN with vision transformers (I haven't seen it yet at least). 
For your source training are you sure the backbone is frozen? If not it might require some hyperparameter tuning for training and/or using a different optimizer, as training CLIP-initialized networks doesn't necessarily work with the same hyperparameters used for ImageNet-initialized ones (as reported in DenseCLIP paper https://arxiv.org/abs/2112.01518).

**Comment by hollow-503** [comment]
Yes，I load the ViT-B/16 pretrained by CLIP and freeze the backbone with the arg `--freeze_BB` in the source training. In my opinion，you only train the segmentation head（Deeplabv3+） in the source training. Am I right？Is there something I ignore？

**Comment by mfahes** [comment]
Yes in the source training and adaptation we only train the segmentation head. I don't know the problem then, please check your implementation and try tuning the hyperparameters for learning

**Comment by mfahes** [comment]
I'll close this issue now. please feel free to re-open it if you have any other questions.
