### ISSUE TITLE
Image classification

### ISSUE THREAD

**Issue by jxthyatt** [astra-vision/PODA#6]
Could you release the code of image classification?

**Comment by mfahes** [comment]
Hi, we don't plan currently to release the classification code. 
However, we used exactly the same script for feature optimization (https://github.com/astra-vision/PODA/blob/master/PIN_aug.py), and for training the linear probe, we used the script provided in CLIP code  (https://github.com/openai/CLIP#linear-probe-evaluation)

**Comment by mfahes** [comment]
I'll close this issue now. Please feel free to re-open it if you have any other questions.
