### ISSUE TITLE
Results for foggy scene

### ISSUE THREAD

**Issue by Jumponthemoon** [astra-vision/PODA#9]
Hi,

Appreciate your great work, very inspiring!

I'm wondering if there is any results for acdc foggy scene?

**Comment by mfahes** [comment]
Hi, thanks for your interest in the work.

During the submission I was testing PODA with the prompt "driving in fog" and it was not improving the source model performance, and I wasn't sure if there was a bug somewhere or it's just not working in this case (While the method is working well for object detection in foggy scenes).

However, in [this](https://openaccess.thecvf.com/content/CVPR2024/papers/Yang_Unified_Language-driven_Zero-shot_Domain_Adaptation_CVPR_2024_paper.pdf) recent paper the authors report PODA performance on ACDC fog for semantic segmentation and it seems to work (please see tables 2 and 3).
